---
# tasks file for vector-role
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "./vector-amd64-{{ vector_version }}.deb"
    mode: "0644"
  notify: Start vector service
- name: Install vector packages
  become: true
  ansible.builtin.apt:
    deb: "/home/mahadev/vector-amd64-{{ vector_version }}.deb"
- name: Flush handlers to restart vector
  ansible.builtin.meta: flush_handlers
- name: Vector | check the directory exists
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: "0755"
- name: Configure Vector | Template config
  become: true
  ansible.builtin.template:
    src: "template/vector.yml.j2"
    dest: "{{ vector_config_dir }}/{{ vector_config_file }}"
    mode: "0644"
